---

spring:
    datasource:
        url: jdbc:mariadb://localhost:3307/ticketsale_db
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        properties:
            hibernate: org.hibernate.dialect.MySQL5InnoDBDialect

...